### ISSUE TITLE
doesn't support trailing comma in trait function signature

### ISSUE THREAD

**Issue by luxalpa** [Zettroke/declarative_enum_dispatch#2]
if the line with function parameters gets too long, rustfmt will separate it onto multiple lines and end each line with a comma like in the example below:

```rs
  trait Deserializable {
      fn des_run_in_server(
          self,
          asdfasdfasdfasdfasdf: i32,
      ) -> Pin<Box<dyn Future<Output = ()> + '_>>;
  }
```

Unfortunately this gives an error: 
> error: method `des_run_in_server` should receive self

**Comment by Zettroke** [comment]
Thanks for noticing it!

**Comment by luxalpa** [comment]
Awesome, thanks!
